### ISSUE TITLE
doesn't work woth Hogfather

### ISSUE THREAD

**Issue by arlt** [dokufreaks/plugin-feed#10]
Error messages in logs after upgrade to Hogfather:

`AH01071: Got error 'PHP message: PHP Warning:
require_once(/var/www/dokuwiki/inc/events.php): failed to open stream: No such file or directory in /var/www/dokuwiki/lib/plugins/feed/feed.php on line 14
`

https://github.com/dokufreaks/plugin-feed/blob/17f3f22b1a8d0139d0a4a92dfae08e7f0a7d1876/feed.php#L14

>In my opinion it seems to work anyway.
Sorry: It doesn't work!

**Comment by GJRobert** [comment]
Hi @arlt 
for me this plugin does not work at all in Hogfather. Only blank pages returned with `lib/plugins/feed/feed.php` (e.g. 
- http://ciangbrides.myds.me/dw-hog-test-plugins-new/lib/plugins/feed/feed.php?plugin=blog&fn=getBlog&ns=&title=Blog
- http://ciangbrides.myds.me/mikio/lib/plugins/feed/feed.php?plugin=blog&fn=getBlog&ns=&title=Blog)

Have you ever seen this?
And how do you collect your error log?

**Comment by Klap-in** [comment]
You have to look for the log of the webserver, please see https://www.dokuwiki.org/faq:blankpage

**Comment by arlt** [comment]
> 
> 
> Hi @arlt
> for me this plugin does not work at all in Hogfather. Only blank pages returned with `lib/plugins/feed/feed.php` (e.g.
> 
>     * http://ciangbrides.myds.me/dw-hog-test-plugins-new/lib/plugins/feed/feed.php?plugin=blog&fn=getBlog&ns=&title=Blog
> 
>     * http://ciangbrides.myds.me/mikio/lib/plugins/feed/feed.php?plugin=blog&fn=getBlog&ns=&title=Blog)
> 
> 
> Have you ever seen this?

Sorry i mixed it up with subsciption.
I corrected my first comment. It doesn't work - same here.

> And how do you collect your error log?

It depends on your setup (webserver, operation system). Here it is `/var/log/httpd/https_error.log`

**Comment by GJRobert** [comment]
Thanks to @arlt and @Klap-in for sharing methods to find PHP error logs. I cannot find error logs for my Synology NAS server, though, but I managed to enable the logging and successfully made the system log the errors in my specified path (ref. [Enable php error logs on a Synology NAS - SKDavis](https://skdavis.net/viewtopic.php?t=148))

I have got the same error as @arlt got:
```
[13-Oct-2020 14:26:16 Asia/Taipei] PHP Warning:  require_once(/volume1/web/dw/inc/events.php): failed to open stream: No such file or directory in /volume1/web/dw/lib/plugins/feed/feed.php on line 14
```

I then consulted [devel:releases:refactor2020 [DokuWiki]](https://www.dokuwiki.org/devel:releases:refactor2020) and see that `require_once` is no longer needed. Therefore, I have checked out my fork and tried to comment out Line 14 of `feed.php`, since `inc/events.php` is indeed deleted sometime in the DokuWiki release, and the commit seems to work. Can you try with my fork to see if it works for you? https://github.com/GJRobert/plugin-feed/archive/master.zip (install on your DokuWiki `?do=admin&page=extension&tab=install` page, with `Overwrite existing files` checked)
